---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation
APPLY_FIXES: none # When active, APPLY_FIXES must also be defined as environment variable (in github/workflows/mega-linter.yml or other CI tool)

EXCLUDED_DIRECTORIES:
  - common-tools
  - report
  - .git

# LOG_LEVEL: DEBUG
ERROR_ON_MISSING_EXEC_BIT: true
SPELL_CSPELL_CONFIG_FILE: .cspell.yml

# Reporter
EMAIL_REPORTER: false
FILEIO_REPORTER: false
GITHUB_STATUS_REPORTER: false
JSON_REPORTER: true
PRINT_ALPACA: false
PRINT_ALL_FILES: false
SHOW_ELAPSED_TIME: true
